# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: poemchoice

description: > 
  playing with NLU of vpod poetry.
# baseurl: "/poemchoice" # the subpath of your site, e.g. /blog
url: "https://uidaholib.github.io/poemchoice"

# Build settings
markdown: kramdown
# Sass
sass:
  sass_dir:         _sass
  style:            :compressed